#!/bin/bash

for file in /tmp/*.log
do
  mv "$file" "${file/.log/.ready}"
done

for entry in /tmp/*.ready
do
  sort /tmp/${entry}.ready | uniq > /tmp/${entry}.ready
  curl -v -F logs=@${entry} -F rasp_id=$1 http://php54-denismosolov.rhcloud.com
  sudo rm -f $entry
done
