#!/bin/bash

current=$(date +%H_%M)

if ls /tmp/*.log 1> /dev/null 2>&1; then
  for file in /tmp/*.log
  do
    if [ "$file" != "/tmp/$current.log" ]
    then
      mv "$file" "${file/.log/.ready}"
    fi
  done
fi

if ls /tmp/*.ready 1> /dev/null 2>&1; then
  for entry in /tmp/*.ready
  do
    sort ${entry} | uniq > ${entry}.unique
    curl -v -F logs=@${entry}.unique -F rasp_id=$1 http://parking-denismosolov.rhcloud.com/history.php
    rm -f $entry
    rm -f ${entry}.unique
  done
fi 
